version: '3'
services:
  app:
    network_mode: host
    container_name: tic-tac-toe
    stdin_open: true
    command:  npm start
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/code'
      - '/code/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CI=true
